<!-- Do not edit this file. It is automatically generated by API Documenter. -->

[Home](./index.md) &gt; [@contract-case/case-plugin-base](./case-plugin-base.md) &gt; [failedExpectationError](./case-plugin-base.failedexpectationerror.md)

## failedExpectationError() function

This represents a mismatch during a case execution that isn't covered by a matcher (usually this is an expectation failure during a MockInteraction which means we can't run the matching engine for some reason).

Most of the time you won't need to use this, because most matching errors come from matchers. Errors encountered during matcher execution should use [matchingError()](./case-plugin-base.matchingerror.md) instead.

**Signature:**

```typescript
failedExpectationError: (message: string, actual: unknown, code: string, context: MatchContext, expected: unknown, annotations?: ErrorAnnotations) => CaseError
```

## Parameters

<table><thead><tr><th>

Parameter


</th><th>

Type


</th><th>

Description


</th></tr></thead>
<tbody><tr><td>

message


</td><td>

string


</td><td>

The message that describes this error


</td></tr>
<tr><td>

actual


</td><td>

unknown


</td><td>

The actual value that was received


</td></tr>
<tr><td>

code


</td><td>

string


</td><td>

A code that can be looked up in the documentation. This should be a unique code specific to this kind of error that users could look up in the documentation for more information.


</td></tr>
<tr><td>

context


</td><td>

[MatchContext](./case-plugin-base.matchcontext.md)


</td><td>

The match context this occurred in


</td></tr>
<tr><td>

expected


</td><td>

unknown


</td><td>

An optional expected value (might be a description of what was expected)


</td></tr>
<tr><td>

annotations


</td><td>

[ErrorAnnotations](./case-plugin-base.errorannotations.md)


</td><td>

_(Optional)_ Optional annotations to provide additional information for the user about the values printed


</td></tr>
</tbody></table>

**Returns:**

[CaseError](./case-plugin-base.caseerror.md)

CaseError

